//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by calc.rc
//
#define IDD_CALC_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDB_BITMAP1                     135
#define shrineButton                    1000
#define jelocButton                     1001
#define ghShrine                        1002
#define sixthJeloc                      1003
#define actualLabel                     1005
#define actual                          1006
#define usedLabel                       1007
#define used                            1008
#define remainingLabel                  1009
#define remain                          1010
#define classLabel                      1011
#define levelLabel                      1012
#define agilityLabel                    1013
#define constitutionLabel               1014
#define wisdomLabel                     1015
#define classShow                       1016
#define lvlIn                           1017
#define classMinus                      1018
#define strengthShrine                  1020
#define strengthJeloc                   1021
#define agilityShrine                   1022
#define agilityJeloc                    1023
#define constitutionShrine              1024
#define constitutionJeloc               1025
#define intelligenceShrine              1026
#define intelligenceJeloc               1027
#define wisdomShrine                    1028
#define wisdomJeloc                     1029
#define agilIn                          1030
#define strIn                           1031
#define consIn                          1032
#define intelIn                         1033
#define wisIn                           1034
#define classPlus                       1035
#define levelMinus                      1036
#define levelPlus                       1037
#define strMinus                        1038
#define strPlus                         1039
#define agilMinus                       1040
#define agilPlus                        1041
#define consMinus                       1042
#define consPlus                        1043
#define intelMinus                      1044
#define intelPlus                       1045
#define wisMinus                        1046
#define wisPlus                         1047
#define healthLabel                     1051
#define manaLabel                       1052
#define baseLabel                       1053
#define oneLabel                        1054
#define helmLabel                       1054
#define twoLabel                        1055
#define armorLabel                      1055
#define threeLabel                      1056
#define glovesLabel                     1056
#define fourLabel                       1057
#define weapLabel                       1057
#define fiveLabel                       1058
#define ringLabel                       1058
#define sixLabel                        1059
#define extraLabel                      1059
#define sevenLabel                      1060
#define helmLabel2                      1060
#define eightLabel                      1061
#define hpbase                          1062
#define hpone                           1063
#define hpextra                         1063
#define hptwo                           1064
#define hpthree                         1065
#define hpfour                          1066
#define hpfive                          1067
#define hpsix                           1068
#define hpseven                         1069
#define hpeight                         1070
#define mpbase                          1071
#define mpone                           1072
#define mpextra                         1072
#define mptwo                           1073
#define mpthree                         1074
#define mpfour                          1075
#define mpfive                          1076
#define mpsix                           1077
#define mpseven                         1078
#define mpeight                         1079
#define spellList                       1080
#define spellsEarnedLabel               1081
#define experienceNeededLabel           1082
#define experienceShow                  1083
#define alignmentGroup                  1084
#define neutralButton                   1085
#define fullButton                      1086
#define loadList                        1087
#define charLoadLabel                   1088
#define reset                           1100
#define strBMP                          1102
#define agilBMP                         1103
#define consBMP                         1104
#define intelBMP                        1105
#define wisBMP                          1106
#define loadButton                      1115
#define saveButton                      1116
#define saveIn                          1117
#define charSaveLabel                   1118
#define deleteButton                    1120
#define hphelmIn                        1122
#define hparmorIn                       1123
#define hpgloveIn                       1124
#define hpweapIn                        1125
#define hpringIn                        1126
#define mphelmIn                        1128
#define mparmorIn                       1129
#define mpgloveIn                       1130
#define mpweapIn                        1131
#define mpringIn                        1132
#define percent1                        1142
#define percent2                        1143
#define percent3                        1144
#define percent4                        1145
#define percent5                        1146
#define percent6                        1147
#define percent7                        1148
#define percent8                        1149
#define percent9                        1150
#define percent0                        1151
#define addition1                       1152
#define addition2                       1155
#define addition3                       1156
#define addition4                       1157
#define addition5                       1158
#define addition6                       1159
#define addition7                       1160
#define addition8                       1161
#define addition9                       1162
#define addition0                       1163
#define hphuman                         1165
#define mphuman                         1166
#define ID_FILE_EXIT                    32771
#define ID_BONUSES_EJCONFIRMED          32775
#define ID_BONUSES_151719               32776
#define ID_BONUSES_212529               32777
#define ID_BONUSES_3439                 32778
#define ID_BONUSES_45                   32779
#define ID_BONUSES_HALLOWEENADDED       32780
#define ID_BONUSES_50                   32781
#define ID_BONUSES_61718191             32782
#define ID_BONUSES_ETC                  32783
#define ID_BONUSES_STR                  32790
#define ID_BONUSES_STR_3439             32791
#define ID_BONUSES_STR_45               32792
#define ID_BONUSES_AGILITY_FIGPALADIN   32796
#define ID_BONUSES_AGILITY_3945         32797
#define ID_BONUSES_AGILITY_RANGERDARKWARBARB 32798
#define ID_BONUSES_AGILITY_293945       32799
#define ID_BONUSES_AGILITY_CLERIC       32800
#define ID_BONUSES_AGILITY              32801
#define ID_BONUSES_AGILITY_WARLOCKWIZARD 32802
#define ID_BONUSES_AGILITY_61           32803
#define ID_BONUSES_AGILITY_DRUID        32804
#define ID_BONUSES_AGILITY_50           32805
#define ID_VERSION_HTECHV03             32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1166
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
